const OrderActionTypes = {
    SET_ADDRESS: 'SET_ADDRESS',
    SET_CONTACT: 'SET_CONTACT',
    SET_COMPLETE_PAYMENT: 'SET_COMPLETE_PAYMENT',
    CLEAR_USER_INPUT: 'CLEAR_USER_INPUT'
}

export default OrderActionTypes;